version: 2.1

executors:
  ubuntu-machine:
    machine:
      image: ubuntu-2204:current
    resource_class: large

jobs:
  build-twrp:
    executor: ubuntu-machine
    steps:
      - checkout
      - run:
          name: Set up Build Environment
          command: |
            sudo apt-get update
            sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq bc ccache \
            libssl-dev python3 openjdk-8-jdk rsync
            
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run:
          name: Configure Git
          command: |
            git config --global user.name "CircleCI Builder"
            git config --global user.email "builder@circleci.com"
            git config --global color.ui false
      - run:
          name: Sync TWRP Source
          command: |
            mkdir -p ~/twrp
            cd ~/twrp
            ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1 --depth=1
            ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          no_output_timeout: 30m
      - run:
          name: Clone Device Tree
          command: |
            mkdir -p ~/twrp/device/xiaomi
            ln -s ~/project ~/twrp/device/xiaomi/air
      - run:
          name: Build vendor_boot TWRP
          command: |
            cd ~/twrp
            export ALLOW_MISSING_DEPENDENCIES=true
            export USE_CCACHE=1
            export CCACHE_EXEC=/usr/bin/ccache
            ccache -M 20G
            
            source build/envsetup.sh
            lunch twrp_air-eng
            mka vendorbootimage
          no_output_timeout: 45m
      - store_artifacts:
          path: ~/twrp/out/target/product/air/vendor_boot.img
          destination: vendor_boot.img

workflows:
  build:
    jobs:
      - build-twrp
